name: Deploy to Docker

on:
  push:
    branches:
      - main  # or 'master' depending on your default branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build and Push Docker images
      uses: docker/build-push-action@v2
      with:
        context: .
        file: backend/Dockerfile  # Path to your backend Dockerfile
        push: true
        tags: username/simple-task-manager-backend:latest

    - name: Build and Push Frontend Docker images
      uses: docker/build-push-action@v2
      with:
        context: .
        file: frontend/Dockerfile  # Path to your frontend Dockerfile
        push: true
        tags: username/simple-task-manager-frontend:latest

    - name: Deploy with Docker Compose
      run: |
        docker-compose down
        docker-compose up -d
